### ISSUE TITLE
Does not find RPis with wireless interface

### ISSUE THREAD

**Issue by tvoverbeek** [BusesCanFly/rpi-hunter#1]
The scan only finds RPi-s which are connected with wired ethernet.
I have several RPi-s on my local network which are WiFi only.
These are not found.
I realize this is inherent to using the arp protocol since arp is for wired ethernet.

**Comment by BusesCanFly** [comment]
Arp is not just for wired connections, but were you specifying your etherjet interface (i.e. eth0) instead of a wireless interface (i.e. wlan0)?

**Comment by BusesCanFly** [comment]
Here's a good link to learn about the ARP protocol
https://youtu.be/4xaWoZE8eik

**Comment by tvoverbeek** [comment]
Yes, arp also works on wireless. However my home network consists of part wired and 2 different wireless networks, all part  of 192.168.200.0/24.
The scan was run on my Mac OSX 10.14 with arp-scan from macports via its wireless interface.
Only the wireless clients connected to the same wireless network and the wired clients will show up, not the ones connected to the 2nd wireless network.
When I switch to the other wireless network the Pi ZeroW and 3B show up.
Clients with USB WiFi adapters do not show up, since they are identified with the adapter chip manufacturer.
This is to be expected the way arp works.
Looking into nmap to see if I can get a scan of the complete network.

**Comment by BusesCanFly** [comment]
Oh interesting! If all you're looking for is to automate pushing commands to all of them, theres a slightly dumb way to do it that works just fine. In rpi-hunter, the arp-scan results are saved to a file in the `./scans/` directory. Just make a file there containing each IP address of the pi on a different line, and specify that file with `--no-scan -f [FILENAME]`
(Assuming all are reachable from the network you are currently on)

**Comment by tvoverbeek** [comment]
@BusesCanFly Yes, I saw the --no-scan option and will probably use it to keep all my RPi-s at the same update level. Thanks for your software
