### ISSUE TITLE
Error running on MacOS Mojave

### ISSUE THREAD

**Issue by soumilshah1995** [BusesCanFly/rpi-hunter#4]
Hello Thanks for making the tool i am trying to run this tool on mac os 
when i try to run i am getting error 

base) Soumils-MacBook-Air-8:rpi-hunter soumilshah$ python rpi-hunter.py 
  File "rpi-hunter.py", line 66
    print colored("Specify with --payload", "green"), colored("name\n", "yellow")
                ^

**Comment by mchester** [comment]
I fixed this for python3 by changing 
`print colored("Specify with --payload", "green"), colored("name\n", "yellow")`
to
`print (colored("Specify with --payload", "green"), colored("name\n", "yellow"))`

**Comment by mm1234mm** [comment]
I fixed this for python3 by changing
print colored("Specify with --payload", "green"), colored("name\n", "yellow")
to
print (colored("Specify with --payload", "green"), colored("name\n", "yellow"))
