### ISSUE TITLE
change adapter

### ISSUE THREAD

**Issue by truesamurai** [BusesCanFly/rpi-hunter#6]
Now its scans on eth0. Can I change that to eth1?

**Comment by truesamurai** [comment]
For now i have found a solution by changing the code:
os.system('sudo arp-scan -I eth1 -g '+args.ip_range+' -W ./scan/scan.pcap'+quiet)

But it would be a good options to include this as a choice when running the program.

**Comment by BusesCanFly** [comment]
I haven't touched this project in ages and its pretty terrible, but if it gets re-written ill add a cli arg for that :)
